name: "pr-auto-state-label"
description: "pr-auto-state-label"

branding:
  icon: "bell"
  color: "white"

inputs:
  token:
    description: "GitHub token"
    required: true
  label:
    description: "특정 조건에 입력이 될 라벨 목록 입니다 자세한 형태소는 readme를 참고해주세요."
    required: true
  deleteLabelPattern:
    description: "glob를 사용하여 삭제를 할 라벨 패턴입니다."
    required: false
  skipReviewerNamePattern:
    description: "glob를 사용하여 해당 액션을 실행 시키지 않을 리뷰어 이름 패턴입니다."
    required: false


runs:
  using: "node16"
  main: "dist/index.js"