name: pr-auto-state-label

on:
  pull_request_review:
    types: [ submitted ]


jobs:
  pr-auto-state-label:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: pr-auto-state-label
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          label: >
            { 
              "comment": "리뷰 완료",
              "requestChange": "병합 보류",
              "approve": "Approve"
            }
          deleteLabelPattern: "{D-*,hotfix}"
